<h1 align='center'>TODO</h1>

### Website:
https://balayokesh.github.io/todo/

### To run this project locally:

**Step 1:**  
Clone this project to your local machine
```bash
git clone https://github.com/balayokesh/todo.git
```

**Step 2:**  
Change directory to the project folder
```bash
cd todo
```

**Step 3:**  
Install required npm packages and run the project at port `3000`
```bash
npm i && npm start
```